install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc -o html/faq.html
- rake check_links
- rake test
env:
  global:
  - GH_REF: Dorlig/ProjetIntegrationContinue.git
  - secure:
  after_success:
- bash monscript.sh
