install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
#- asciidoctor faq.adoc -o html/faq.html
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc -o html/faq.html
- rake check_links
- rake test


env:
  global:
    - GH_REF: Dorlige/ProjetIntegrationContinue.git
    - secure: F8OX44fz2KkfIFsFQj/AvtoSAe/7oYZNSxnLJUjG1jzahXRzJwv0Y9Sy/zoWf3N8B01gHLKurQoy4ryxrgzIl5nucI6jVGw+lpcq9YOz53Z1LzXOcqisM4b4JucL5XMUV9jJaG1QVoNEMzZAQn/A+IkBwda/QXTZmhlXyKmXcT6nax8PWdlZgN6Vai/2PHIOi3S7N3wFecVGHWQcQ0nIIWli+KPFgq7gNGoryZBMrEs74ikXzpjmlAunM+i5khKNNOK2mFm1urNg8t6oCFXkO0U2jRyVpa1WsuJMDCEMrxVQ8lBy9hP0RNzlEhxRDlAXvM/l6KQNh/771Je8pXCk8t4wDHD/zswSeB9kMoGnEjoVA90CSvk1AMqVHqia3uSUD3LZ07+fAwXYockQalczddPg93k7C3tjVb1tuph9U5O10s5N+5hN6RzmgJjlMml5bFjszao9MKUB0Y5/y0wO3FmpKZhTdZ1gFJDIKuIpZKK9aL87yTw1mowOZlo71FHMOYYKcqrfNJ8hBssE6JaXmQoIu9C6g4AR0G70090ufzWcVk1lUXAEp0I/EOXnez2J9eYgoGKB/V5xBMqSEU9DqriGNbauH7jkgX7t/QyH4u2sjWoN+TtxWjW6Z5ILc2NrjrMxpjD4Vz09aiE/b2BmcHq5IWJGTT348lf8+tXInmo=
after_success: 
- bash monscript.sh
