install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc -o html/faq.html
- rake check_links
- rake test
sudo: true
env:
  global:
  - GH_REF: Dorlige/ProjetIntegrationContinue.git
  - secure: coqkyVkQq+ph/HUY+BEfnpcnxXGwmn/v404qXX9bGshgi2zI92eMDDgyF1G05ZaGulwWinj7g43KlWeFLOlD2gsGAacHTYR8Guz+xcch+EYcGs1l1/hzBbXKtb+LoL2Rd6RDz+LGiUEXe1teZpOHHFHdfTI2PDPRUnmmtM7FBSWdMOOo+3wQUFUkAJMLHx3XZFsbNZOp5lTRQgWrmGkfLFarYBKo3dQzsTm9IhHHmDSokBFwa+tJoiMmyYgGnUEXxJLJ3emoKf6tW3Ha+y5LDXWvHCc3qL68ydChkDDfV2VurSJleiamruHsEPU/EoFveNYws4kSbbVb8wP/nr+bez8yy9NGOAhs8urrzGo5UX7IRugLxwV/uBlylVRN4UtQm+MrWoimXT4G1fii5Hih0QjjJzGSxARZvDUsYPn3g771hLRM8yJ9MrNK5B32NMK0ifs7zzET9uwJeX4Yuk3CULk/C3HrXDwXH8LX29FSgOdYaaaTavm6ACZ9zenJidWmpjbNFTwbC8vK0R3hjhPqHAEWT5vt1eY6526Tm7NfmFq1dI/Abb3A9vo7ZSnj0t99N6SSv8txk8G94KhlMPU7jdNg2s3O7kdwQ5sFRE+n3jUD8DJ9gPJy0fbR7iyFTB5yOsajouq0Os7tQYTSN5sZ7cXLHjJOBAJAV6XKp7z0xus=
  - secure: OHRHtqPLiT2f2UCx9VM/99VVtmUCinXTYEvxvblKWGQCAXtJhxPcGBRO/9fGWAnBU+MvqYpvPs86LHC9+pqT8xRi0IVHLqLwVzxhL3fUV+KB4so7pVqBvn/4oB2cm6v8LhN8NDeQrTvcUUDFYzIS7UjPjN0Jes38OfQlb01WeqsofNJLsYVvy8vfvyoD60S3Q+fXjqTqv54uTy1UMKQdcEdh9MOH12Eyqu2UmM004Hw3yUPXB8+S8l77EXSiyCG3RwnbNAwcZHRt54UmlXnrk25TZjY50xFYbUVMx0xpFrb5uquHxb2f+924jCg1VdeIwivIYFFLm/tDjf7awM1dJHovl0ZpdaGaN/jfPjH6frkbmXLlC5myrHCOiK2ULK1Lin64XbKzJqx5S3BOvBOTsVwWzDXpvdxTMy7PHBjIkPH5K6TBn0CEqUQ3LM0l1uJh3GEeFb8arUX3GktcgywD4rGAycpdP6HXIpWd75m8ltjT1HVUoCmT/rjRsErIyYOljqlG3b0BM06i3lG/NPHgKukO0xehEgmFj47vqtLAHppRd4oNLtvmPnUCdjhsJN9HkLxcFD94wHbkHWiy8EfhZBTJajyj5YWjSp3TBFe958Z9+RPjDBHCjexrU3xfZiXy9D83zLrMkCPjZzE4WseRAo2+xqDiP+hgCV9luy0biX4=
after_success:
- bash monscript.sh
