install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
#- asciidoctor faq.adoc -o html/faq.html
- asciidoctor faq.adoc -o html/faq.html
- rake check_links
- rake test


env:
  global:
    - GH_REF: Dorlige/ProjetIntegrationContinue.git
    - secure: Ggi+jwUA5enjH5B3dbsQH/3eB5Vb/arxIcilUFWvYDU2e/HwKsjdhwu0CbxWMHKhOPfLba+gXX4j3deqyjCzBZL1jBZzao1NAox7lSB6qzZEmRibD2Jw9I4Hipmz4+X15tGzdDxsovN2NHkalmdP8x75g95uUBbLOqICUReg1uoUnJVIz5Yg9OY5y2Rf858S/Jzz/Ms0Am9CazCUOcdYjpZlsMaPyQZTXS4tLd2wStVxSg2yVW9F40Xy5OJhZENl/pVUi/T32BgLG1HpRdVihff9Nxej9/diReSduLypwBjuBIjAvtfh0FPE14eeYH0doeKe3Zy/dbavKWyavlYm9uCtxTPAbP5eiUMlit8qw0uLUn0Oj0TKnz2PiHf4eHW6KB8tn3OI24+IpOA4hwfdSradth3V35VxL+EKOJn6NssbTbnf28n4IWvptmfulWgm6WhZ1JxcS+bTKGJdKWuK/DDD0wZqZC8hH6U8vgyk0/PNNFjsz6NF/+I3lC8cT6jBaN+Zx+/1E3dDuUivdZyUDfFOa2+UIKyj48Mjot461/XB6CUMJxYXDPDfpVd1QLrZhaAJYwY3G+b1Y4QK8FRqPZ6h9b/qlJLzRUtYWHmsu+Lv5G2PmCVoexNSkpkKc+V2MbPQV0QQT7LCdTyfkpYrOaH3MMbPydrMPgsWO04jJkk=
after_success: 
- bash monscript.sh
