install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc -o html/faq.html
- rake check_links
- rake test
sudo: true
env:
  global:
  - GH_REF: Dorlige/ProjetIntegrationContinue.git
  - secure: t85x/mi4UmWjpozICzGkKb9ui6JZHxjOes8pes2qW4bAbH8VFIIqPTdtFX0QH0uMlDqZw6RW+9Z9re2ZkLO98FQDIzcFY4eNkK4uoA+lOWIove2g6IHsU2H09eJKAeVGkdepORs85+RIdozdN0ub/zsuP3zOcX5j3EcZgKRFbpL6uzwfv4ODkEPoCb8reWBcBLBDoJAv7pbBq96j+cQegsTRB5xJtLiqKDJ7c/pgQUbAwH/vXArXdSV7XuaTNTDDgrpasuVcvKyppZH0JokJFzhD2yJv6rdU/fjFQN7wH0XvHIJjp9t4qp0dnLR+L9RuLqkAXVQPJXBnIZQPggJ4c1LGlXfD9tcH8iArOwc6W5lwNaZtiiCvMA2cTL9UxnaqDJmTZ++l7ZADM6d5M1DUAVbplx6M3mXzc1MJTWaMGEzbIqXxqxR954q3w0Bjwy+ZnerIy0gBfRI6iJYZSaqJKZfnag8qcKGXXhrM4OQmxD3SuyXN1063s1KWIX/19EALKNyFTFoJpt4QpuR8yG3TyO/FEgTpRVjcBIHdtj1T3FcW26WExnA4suHDtRd/a0+Lg1Ma6K2tBEjKQeHqFzoTGztC/YJZ2lZq9+2TkOlViZ65Sl2XIVKsmqpte8xh/G6bNDqZt+QRk7QCN9rgMdKsdJ04g5a0EC/I74HKAMZYxP4=
after_success:
- bash monscript.sh
