install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
#- asciidoctor faq.adoc -o html/faq.html
- asciidoctor faq.adoc -o html/faq.html
- rake check_links
- rake test


env:
  global:
    - GH_REF: Dorlige/ProjetIntegrationContinue.git
    - secure: u5XyO7oh3PtkQwMRqQ5a3ZjphqjcdwfhIsI1Mspz6MlZ2TqkQg07ZeDdd+w8rgii+L1OEYM+SQnLSDOLpLFTbLKVhhFDNMddcMuj7U4TV+fAVd234aQ5cLp1hSKuDhsgcMLomqHM9mKhdEdekWdFQJBcGv+ok01IZ/WF9/e5b8CZakg3t9gou7ZWhxZ6bSncFG7JMUQXf0TmBAFNyvf+DpU6TPevgoJy6iDfihuKSBVLF/smm+8FZY5b1t0zGcdqkjntwkJYJz/2lJbrVtktSzMRjhqQcKA9ZFgwlnKPCvdQhKFexq1rkoOZX9AWH9utisY9W3ntHVxfw0s+Aa4E7X3iL61J4pdBvFxcDXNcQaR6f+k1eDz5lRp3h5UoY2NpXq9rR+pwRp9D7t12LoVxkJtlUrTbR/MeUaXJOnZ4atz4IQ89E+n9lj8sj+y3PvJJAddXwG0MkfZW670jLAI3pN6GHsyndj6jdN9AcsxEcylsEd9wgeKIDdGGWcGindjV2xu0Zl2prXp5GInyan6qPnvW3sK1pMNXme/1S7limg2sYEHWqYUWalp7bZ3Ljui80s3eQgWWD39F3mFO/B4gwbv7ZYAr5w8S7R5CgYcPbPO2DKD6M7Nney45LVRMcjimogIIq3Znd/NGglq51bRhMo2mV83l4efrbyDFVYuumpk=
after_success: 
- bash monscript.sh
