install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc -o html/faq.html
- rake check_links
- rake test
env:
  global:
  - GH_REF: Dorlige/ProjetIntegrationContinue.git
  - secure: s5B6G/IY1AKS9y7oSOZk1dA/M0zake+EAwGdud6ClI94Og+UCBqDMn7GiuvRHGo3L2g7EEAelBZOFTlJtno4DhrUBAm3uMiAWnVA76S4uzqBDhDvkG1Tt1RuoCERERoy994cZG8k4nqFuRmNsjpxoM/wqlstA+M5cgACQyMr/s1hWVMLtp/JxfezJI5robwLMZ/NSISUsIz9Glp7a/0Y3iZ9mcYfA3sjN/XPup0JK1qW+9G6GMtkApxbNj3HcGJt2lLX1xl41mEE3Eo+wMndTFBVdMMs0vuoTPgXDuSnGHcLKIZ/uNj1pRppPujvK2UwGGK0TFFEhdIhW9IoYF+4x0thUeHYP9nodDoXn+rm+G5/c+4J0pXIb0IxbpTBj0su9iKBxaSgaKUzAMI8yXm0c4VKUejVpBr5KlyjceGeGrh4QSLL+l4Lmh9Asoxe5SUgIeBs8osXH58PLXVNWBiRE5OEmV3Seh9sSkAjZqHtfB/nayqx1bI+U9UGDq2GfMcMUHBx3Im9FTHsXnoMu9FqEnsJGn+F0vmFNpqQVK2I3QSwrYf/xXMEfJ3Bi/96gKfPTwiEMQ2has1BfMPxt0G/D5lCeqeE3aHMDqkE0GcNYG+ol7NTAvnsuk/kJPF/MMU4KCTKBGeUj84/Fi9dhevA41tvcA2AbQTAdb7+Q1Vd7pw=
  after_success:
- bash monscript.sh
