install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc -o html/faq.html
- rake check_links
- rake test
env:
  global:
  - GH_REF: Dorlige/ProjetIntegrationContinue.git
  - secure: kZVP0sLlkL6TVR8CK7YGpw+gPMyE1+jUrhxbj0oNdOH6rIZ26zJxkWubH8ezizl/qi++b45QPczhKSnfXxGe7nZXGC/C9M+Ts+DFdnqoR2gsOo9wYv91V30Sy3ALwHWLkTuAPRdNKqrWMPEMzSFrfll1mXgp8PgVfycben/J+qOP6bCIuv0VPxzVgrztgtAY+jF1uY7p3qdvsuqqLVQUwGgV7ko5vg5yheOj0FHJWe/hIRY00m5UkQk2cXWN3WbqB2iyPSNbRFT6jfDpvcYBzx/h8DfsbJLdpPSlGQYbeCtqzP1UWAwUC/tR+zO9e4HgSfkc35iQvripB/+Op6KVudwrkxKmUDpjqZRBSqjHMo4Qkd/CLkFTx59eUeMcz7nWUkPXdd2wpjvOoY+BL/nfHALHaSnUxkcIXh55ESMebjwkp0n4VgiHAvMrcR01c51XKknBjTS9pFkfH0YuXpGc1Dle6ZTdyUbBDJnXAC608vAcAGllrXHUCgR38vlaKZn31qMU73SyiGK1f6x6otmbLsMP5VKb0xOxfS0lpSZeRRNbA4nxc9+UVTi7wllftBsN6Ubwpsx9U3JCLvA95KQV7gfN5Ppg6QhdHb6J29Wr6fCJpzmwSNRxwKMGygN6sh32ff67TKT5GTB/LMKZNywMMwyPys5GrXbn9UE1qWetoeQ=
  - secure: Cj36+AcKKAovazKumq2QQSEqWw8ElyKyMhScGsDT1bMCl4AjH8/WyQVCAD+PU65CPPAriYzU0JsBk+L0PwLT8ew6HcWVfNNZoB8CdkN59HzSR/KYiMKPEwzv92iEbMvKJcDTmP11S0VYrwNyNr14bieL523Yd3qHBac5+doPjEyvX3mAomUXvRLok6KxFnbfLTymSmtaIspmECOfWhb5AG7HWWy/jSw5r/7XzTSrjpM5QTKkNfabidBHwb+KCO3GhgmZL303NBi44StSgz8zZJIYZ1JsHMMj3XojEEmi1Eew+Tf1Hduq2AYHFBiB2DT0/FWVwjsJqzoRfshDk07JPsyIil440jEWPdDxQtMNVIC91d627AKpApaNLmQ6p7DUizDtrxTq7BRwtY3zOlSEdkuPKmTVAzPottVvDk8he1pGVTGP14Ck+rv982IDYtbFSJ4jnF8gb46ffaS4953nfoWlmNw9ZGldokiU5J6ETvo4j51dexODEmUxB7gPQFElNpDhHnJmDTngp8tPBjuGA7C0XJ28KkVzFJpmTqts4cWNy1i/Ck5aFy1SiMjI+iAmW1UKuJyFT2UIuVuy5Al2TdeOnfcRdj3xZ6o64wUjo1aXGNjihb0tZER233zj2t3C4kV3CvZ5yaVRVJm/6bEpVb0vLRyxdZY3Jlsld4EKNdU=
after_success:
- bash monscript.sh
