install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc page2.adoc page3.adoc -o html/faq.html -o html/page2.html -o html/page3.html
- rake check_links
- rake test
sudo: true
env:
  global:
  - GH_REF: Dorlige/ProjetIntegrationContinue.git
  - secure: t85x/mi4UmWjpozICzGkKb9ui6JZHxjOes8pes2qW4bAbH8VFIIqPTdtFX0QH0uMlDqZw6RW+9Z9re2ZkLO98FQDIzcFY4eNkK4uoA+lOWIove2g6IHsU2H09eJKAeVGkdepORs85+RIdozdN0ub/zsuP3zOcX5j3EcZgKRFbpL6uzwfv4ODkEPoCb8reWBcBLBDoJAv7pbBq96j+cQegsTRB5xJtLiqKDJ7c/pgQUbAwH/vXArXdSV7XuaTNTDDgrpasuVcvKyppZH0JokJFzhD2yJv6rdU/fjFQN7wH0XvHIJjp9t4qp0dnLR+L9RuLqkAXVQPJXBnIZQPggJ4c1LGlXfD9tcH8iArOwc6W5lwNaZtiiCvMA2cTL9UxnaqDJmTZ++l7ZADM6d5M1DUAVbplx6M3mXzc1MJTWaMGEzbIqXxqxR954q3w0Bjwy+ZnerIy0gBfRI6iJYZSaqJKZfnag8qcKGXXhrM4OQmxD3SuyXN1063s1KWIX/19EALKNyFTFoJpt4QpuR8yG3TyO/FEgTpRVjcBIHdtj1T3FcW26WExnA4suHDtRd/a0+Lg1Ma6K2tBEjKQeHqFzoTGztC/YJZ2lZq9+2TkOlViZ65Sl2XIVKsmqpte8xh/G6bNDqZt+QRk7QCN9rgMdKsdJ04g5a0EC/I74HKAMZYxP4=
  - secure: GB0dA0X07qe8P2Y93PM0IfcYdMupzBM2KTMOb6skTXGDwfdgnBovAw1RMuT2Urh19DTK/U7f+AJNkZbTvcgN3J6s7vAFzQxqVgcepXdgcvp+BoZxflYa0oKCqwm0cgMvz+6E5t1qcY2zCXsdmFsNNbjujAg054vV54yrut7NnWNqgtaHp/JxyOUB3hGRNTZCPIb+JkE1b+fGKA4pckoY/HV1901IOYcEqWYsGwD06rauSJb/SGxhJ/CmEuKf+7ZuVgmIhUTCT3F6lpEfZ0zn4MqnfBPgv1LuqIxQ6TXNPHHvoy7GtntFv2mqEnuqGq3s0Aq7v1RrovBNNoD9oGs5WaAg1KmidZp2ye9JQ7VLQof+jYUDRgkQgJe/FUeaaec2DSmuNYICZ8MpP3iVPhXWJutyUK7aedKCUoy6hfr5QYCKvg8rXtvSrjEgfZGcLQDWRUSIZig6rDPNTYrA+nc6/TjjQrpo6aZUPHxZqMwvP3I7GdqMGMfC9R5+v/2fYiaQlUs0+60zAOk5lqaBvPXA6ftrok64Xh+XwRWTteiBqnBSL3R+CbD0wGMM6qLiuPQ+a1HJMC0G+8M7vROIZMUFzuVvzvVTgqc8xtGS8hV70D+YF4sUmfSKEMKjjb/9JqHpgQVUoQdDUrIczfG6N3bz9ylW2bsPGS0LC0gr79xlsKc=
after_success:
- bash monscript.sh
