install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
#- asciidoctor faq.adoc -o html/faq.html
- asciidoctor faq.adoc -o html/faq.html
- rake check_links
- rake test


env:
  global:
    - GH_REF: Dorlige/ProjetIntegrationContinue.git
    - secure: rFzQWd+dpugarHds3ElqCrUmRYb/3ioKLSYoCGPi+jPKgzFqQw1mCwQEZwLjS5CPXrenZV8z9Pv/P/fVfxVb+JPn+TKOkBiJHvAWVdUhoJw0u8OAiWIKuww0T9LYa/LjZHYkTyyFQvfqxITw8l+3Yrj+FS1d6NCCLyDzGrd8aLKJq8BVzqT7RUyUvkYcrdDWHypd6HkdY+YaA4vkeW6ipf7+jiegg/A2I6AEZdwWDQt6RyTKwqFQ62EHuGCFyBC8U5j7nu8NzW7e1E4PtTMzqt7tTLEjikUzAeHLkNEJdaFie8AtIJ9MoYqpfGyhjLSLKuLPZ0a6vmmKXGdAxP0W+RuyjNjUqg8YVUTETLg7n77JvhPVVcvc2BA6fskGEpIr7c71tilnzlNkFm53cZ9TsJjlv0T/uMNsNrys6Lfr85JHf0YC9GmqB3hPPcurdX9HaKiW4u1Y9AR1p9QEQst6DNx6bmys5rroD2l64AUK3e6mOaEvxRetp+Djo6annlfohUsJDYlBt1i/z/bvz91MnnnTQU16+ke2JvPOm6k9ljdDO/J4o6QH90ravaNH5H3g8InCDEC4CajswK2L8kwFgfZnhRTI6v4z38d6NjecmUEQL+uc3jenzwW2TuDlaFCYgIfhmvahba+QuK/hPuH5iKIrmU+Lpn8k6956vYdaZt0=
after_success: 
- bash monscript.sh
