install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc -o html/faq.html
- rake check_links
- rake test
sudo: true
env:
  global:
  - GH_REF: Dorlige/ProjetIntegrationContinue.git
  - secure: Cj36+AcKKAovazKumq2QQSEqWw8ElyKyMhScGsDT1bMCl4AjH8/WyQVCAD+PU65CPPAriYzU0JsBk+L0PwLT8ew6HcWVfNNZoB8CdkN59HzSR/KYiMKPEwzv92iEbMvKJcDTmP11S0VYrwNyNr14bieL523Yd3qHBac5+doPjEyvX3mAomUXvRLok6KxFnbfLTymSmtaIspmECOfWhb5AG7HWWy/jSw5r/7XzTSrjpM5QTKkNfabidBHwb+KCO3GhgmZL303NBi44StSgz8zZJIYZ1JsHMMj3XojEEmi1Eew+Tf1Hduq2AYHFBiB2DT0/FWVwjsJqzoRfshDk07JPsyIil440jEWPdDxQtMNVIC91d627AKpApaNLmQ6p7DUizDtrxTq7BRwtY3zOlSEdkuPKmTVAzPottVvDk8he1pGVTGP14Ck+rv982IDYtbFSJ4jnF8gb46ffaS4953nfoWlmNw9ZGldokiU5J6ETvo4j51dexODEmUxB7gPQFElNpDhHnJmDTngp8tPBjuGA7C0XJ28KkVzFJpmTqts4cWNy1i/Ck5aFy1SiMjI+iAmW1UKuJyFT2UIuVuy5Al2TdeOnfcRdj3xZ6o64wUjo1aXGNjihb0tZER233zj2t3C4kV3CvZ5yaVRVJm/6bEpVb0vLRyxdZY3Jlsld4EKNdU=
  - secure: coqkyVkQq+ph/HUY+BEfnpcnxXGwmn/v404qXX9bGshgi2zI92eMDDgyF1G05ZaGulwWinj7g43KlWeFLOlD2gsGAacHTYR8Guz+xcch+EYcGs1l1/hzBbXKtb+LoL2Rd6RDz+LGiUEXe1teZpOHHFHdfTI2PDPRUnmmtM7FBSWdMOOo+3wQUFUkAJMLHx3XZFsbNZOp5lTRQgWrmGkfLFarYBKo3dQzsTm9IhHHmDSokBFwa+tJoiMmyYgGnUEXxJLJ3emoKf6tW3Ha+y5LDXWvHCc3qL68ydChkDDfV2VurSJleiamruHsEPU/EoFveNYws4kSbbVb8wP/nr+bez8yy9NGOAhs8urrzGo5UX7IRugLxwV/uBlylVRN4UtQm+MrWoimXT4G1fii5Hih0QjjJzGSxARZvDUsYPn3g771hLRM8yJ9MrNK5B32NMK0ifs7zzET9uwJeX4Yuk3CULk/C3HrXDwXH8LX29FSgOdYaaaTavm6ACZ9zenJidWmpjbNFTwbC8vK0R3hjhPqHAEWT5vt1eY6526Tm7NfmFq1dI/Abb3A9vo7ZSnj0t99N6SSv8txk8G94KhlMPU7jdNg2s3O7kdwQ5sFRE+n3jUD8DJ9gPJy0fbR7iyFTB5yOsajouq0Os7tQYTSN5sZ7cXLHjJOBAJAV6XKp7z0xus=
after_success:
- bash monscript.sh
