install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
#- asciidoctor faq.adoc -o html/faq.html
- asciidoctor faq.adoc -o html/faq.html
- rake check_links
- rake test


env:
  global:
    - GH_REF: Dorlige/ProjetIntegrationContinue.git
    - secure: bMuWqGTv1Y63W3nWQU76/x+IcxRdro8wHq7wFPzmJExAXhaD7pnDjkxqjEDoIZl6XbPoduc6nfi6Rb14xatc5BxO5ncUyWoCf6TXJZYwZyeDA2BnY0mbsMUTRF1tRBBc5jiaD0UBPOsedIX03KSIcO+5WIaMsvtJTZ+DqdUjQZxVkSIopINSbs7ZWiRDx2WuYbnw07/IbEo1GhHi+6CN2drNNFZq4EVmeSk1SkWiGbPx7sgLcKJ0Y05GdjincYJNwsmwAx2wy1mN4FltDjEm3GsJdnjPakbNqhpZp0op87C+cU8ddEDmGSq1Ceh0Q5RhJpAk/YBIxW136JFmRXpQDg+5yb3l99KOAbjnjSO03RcKMwV8hMg5X/xRXFixbj7esVXAmcWipAxnA+MmpYrzIHVLpL7l9QRwRtqXCzgGkNnM7CDHQiJzY0g3oDjwF/bzbRXzwoT/z5rjvJTleLKMdEIuU3NjIeTh3/3Az28p91AlaOpDfB5JNAsIuTBPBC+wCzRuIb0OtzlNeurOei31l/7eEiVr7XL2r0VPHbRwuZ8BHaiztoNPrA6xcM4OzOVaZUqVjnPgtff+kvQn/KlGtL//slJH/HWOcZiMkLQcidhzE+QMMkGwcM3IAXkI3mhZNjVetiaTFLcG2g24sbK0xh6OjejdqfVCLCJuPm4fMr0=
after_success: 
- bash monscript.sh
